[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
]

# Compiler settings
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing
gas_reports = ["*"]
fuzz_runs = 256

# Formatting
line_length = 100
tab_width = 4
bracket_spacing = false
